//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPTV.modeles
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAPO_ACTIONPOINT_OPENINGHOUR
    {
        public decimal IAPO_IORA_IMPH_REFERENCE { get; set; }
        public string IAPO_IORA_ACTION { get; set; }
        public int IAPO_SEQU_NUMBER { get; set; }
        public string IAPO_FROM_WEEKDAY { get; set; }
        public string IAPO_UNTIL_WEEKDAY { get; set; }
        public string IAPO_FROM { get; set; }
        public string IAPO_UNTIL { get; set; }
    
        public virtual IORA_ORDER_ACTIONPOINT IORA_ORDER_ACTIONPOINT { get; set; }
    }
}
