//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPTV.modeles
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPH_IMPORT_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPH_IMPORT_HEADER()
        {
            this.IORA_ORDER_ACTIONPOINT = new HashSet<IORA_ORDER_ACTIONPOINT>();
        }
    
        public decimal IMPH_REFERENCE { get; set; }
        public string IMPH_CONTEXT { get; set; }
        public string IMPH_OBJECT_TYPE { get; set; }
        public string IMPH_ACTION_CODE { get; set; }
        public string IMPH_EXTID { get; set; }
        public decimal IMPH_PROCESS_CODE { get; set; }
        public string IMPH_CREATION_TIME { get; set; }
        public string IMPH_PROCESS_TIME { get; set; }
        public Nullable<decimal> IMPH_PROCESS_RETRIES { get; set; }
        public string IMPH_DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IORA_ORDER_ACTIONPOINT> IORA_ORDER_ACTIONPOINT { get; set; }
        public virtual IORH_ORDER_HEADER IORH_ORDER_HEADER { get; set; }
    }
}
