//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPTV.modeles
{
    using System;
    using System.Collections.Generic;
    
    public partial class IORA_ORDER_ACTIONPOINT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IORA_ORDER_ACTIONPOINT()
        {
            this.IAPO_ACTIONPOINT_OPENINGHOUR = new HashSet<IAPO_ACTIONPOINT_OPENINGHOUR>();
        }
    
        public decimal IORA_IMPH_REFERENCE { get; set; }
        public string IORA_ACTION { get; set; }
        public string IORA_EXTID1 { get; set; }
        public string IORA_EXTID2 { get; set; }
        public byte IORA_IS_ONETIME { get; set; }
        public string IORA_NAME { get; set; }
        public string IORA_DESC { get; set; }
        public string IORA_SHORTDESC { get; set; }
        public string IORA_COUNTRY { get; set; }
        public string IORA_STATE { get; set; }
        public string IORA_POSTCODE { get; set; }
        public string IORA_CITY { get; set; }
        public string IORA_DISTRICT { get; set; }
        public string IORA_STREET { get; set; }
        public string IORA_HOUSENO { get; set; }
        public Nullable<double> IORA_LATITUDE { get; set; }
        public Nullable<double> IORA_LONGITUDE { get; set; }
        public string IORA_COORD_TYPE { get; set; }
        public string IORA_EARLIEST_DATETIME { get; set; }
        public string IORA_LATEST_DATETIME { get; set; }
        public Nullable<int> IORA_SERVICEPERIODEXTERNAL { get; set; }
        public Nullable<short> IORA_OH_TOLERANCE_CLASS { get; set; }
        public Nullable<int> IORA_HANDLINGTIME_CLASS { get; set; }
        public Nullable<int> IORA_HANDLINGTIME_ADDITIONAL { get; set; }
        public Nullable<int> IORA_PRECOMBINED_TOUR_SEQUENCE { get; set; }
        public string IORA_TOUR_POS { get; set; }
        public Nullable<byte> IORA_SERVICE_IN_INTERVAL { get; set; }
        public Nullable<int> IORA_CUSTOMER_INDICATOR { get; set; }
        public Nullable<int> IORA_CUSTOMER_GROUP { get; set; }
        public byte IORA_NOTRAILER { get; set; }
        public byte IORA_CODRIVER_NEEDED { get; set; }
        public string IORA_VEHICLEREQUIREMENTS { get; set; }
        public Nullable<decimal> IORA_MIN_VEHICLE_GROUP { get; set; }
        public Nullable<decimal> IORA_MAX_VEHICLE_GROUP { get; set; }
        public string IORA_ADDITIONAL_VEHICLE_GROUP { get; set; }
        public string IORA_PHONE { get; set; }
        public string IORA_EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IAPO_ACTIONPOINT_OPENINGHOUR> IAPO_ACTIONPOINT_OPENINGHOUR { get; set; }
        public virtual IMPH_IMPORT_HEADER IMPH_IMPORT_HEADER { get; set; }
    }
}
