//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPTV.modeles
{
    using System;
    using System.Collections.Generic;
    
    public partial class IORH_ORDER_HEADER
    {
        public decimal IORH_IMPH_REFERENCE { get; set; }
        public string IORH_ORDER_TYPE { get; set; }
        public string IORH_EXTID2 { get; set; }
        public string IORH_CUSTOMER_ORDER_EXTID { get; set; }
        public string IORH_NOTE { get; set; }
        public string IORH_ASSORTMENT { get; set; }
        public string IORH_CUSTOMER { get; set; }
        public string IORH_CONSIGNMENT_EXTID { get; set; }
        public string IORH_LOGISTIC_EXTID { get; set; }
        public string IORH_PRECOMBINED_TOUR { get; set; }
        public string IORH_PREASSIGNED_TRUCK { get; set; }
        public string IORH_VEHICLEREQUIREMENTS { get; set; }
        public Nullable<int> IORH_PRIORITY { get; set; }
        public byte IORH_CODRIVER_NEEDED { get; set; }
        public Nullable<int> IORH_TRANSPORTPERIOD { get; set; }
        public byte IORH_SOLO { get; set; }
        public Nullable<double> IORH_WEIGHT { get; set; }
        public Nullable<double> IORH_VOLUME { get; set; }
        public Nullable<double> IORH_LOADMETER { get; set; }
        public Nullable<double> IORH_QUANTITY_1 { get; set; }
        public Nullable<double> IORH_QUANTITY_2 { get; set; }
        public Nullable<double> IORH_QUANTITY_3 { get; set; }
        public Nullable<double> IORH_QUANTITY_4 { get; set; }
        public Nullable<double> IORH_QUANTITY_5 { get; set; }
        public Nullable<double> IORH_QUANTITY_6 { get; set; }
        public Nullable<double> IORH_QUANTITY_7 { get; set; }
        public Nullable<double> IORH_LENGTH { get; set; }
        public Nullable<double> IORH_WIDTH { get; set; }
        public Nullable<double> IORH_HEIGHT { get; set; }
        public Nullable<double> IORH_NUM_1 { get; set; }
        public Nullable<double> IORH_NUM_2 { get; set; }
        public Nullable<double> IORH_NUM_3 { get; set; }
        public Nullable<double> IORH_NUM_4 { get; set; }
        public Nullable<double> IORH_NUM_5 { get; set; }
        public Nullable<double> IORH_NUM_6 { get; set; }
        public Nullable<double> IORH_NUM_7 { get; set; }
        public Nullable<double> IORH_NUM_8 { get; set; }
        public Nullable<double> IORH_NUM_9 { get; set; }
        public Nullable<double> IORH_NUM_10 { get; set; }
        public string IORH_TEXT_1 { get; set; }
        public string IORH_TEXT_2 { get; set; }
        public string IORH_TEXT_3 { get; set; }
        public string IORH_TEXT_4 { get; set; }
        public string IORH_TEXT_5 { get; set; }
        public string IORH_TEXT_6 { get; set; }
        public string IORH_TEXT_7 { get; set; }
        public string IORH_TEXT_8 { get; set; }
        public string IORH_TEXT_9 { get; set; }
        public string IORH_TEXT_10 { get; set; }
        public string IORH_TASKFIELDS { get; set; }
        public string IORH_ALTERNATIVE_DEPOTS { get; set; }
        public string IORH_PICKUP_EXTID1 { get; set; }
        public string IORH_PICKUP_EARLIEST_DATETIME { get; set; }
        public string IORH_PICKUP_LATEST_DATETIME { get; set; }
        public string IORH_DELVRY_EXTID1 { get; set; }
        public string IORH_DELVRY_EARLIEST_DATETIME { get; set; }
        public string IORH_DELVRY_LATEST_DATETIME { get; set; }
    
        public virtual IMPH_IMPORT_HEADER IMPH_IMPORT_HEADER { get; set; }
    }
}
