//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPTV.modeles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRANSFERDB_TESTEntities3 : DbContext
    {
        public TRANSFERDB_TESTEntities3()
            : base("name=TRANSFERDB_TESTEntities3")
        {
           // this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IAPO_ACTIONPOINT_OPENINGHOUR> IAPO_ACTIONPOINT_OPENINGHOUR { get; set; }
        public virtual DbSet<IMPH_IMPORT_HEADER> IMPH_IMPORT_HEADER { get; set; }
        public virtual DbSet<IORA_ORDER_ACTIONPOINT> IORA_ORDER_ACTIONPOINT { get; set; }
        public virtual DbSet<IORH_ORDER_HEADER> IORH_ORDER_HEADER { get; set; }
    }
}
